title: "Sections"
description: |


patterns:
  guest-names:
    title: "Guest List Names"
    description: |
      Placeholder names for the guest list.
    fields:
      - name: name
        type: string
        example: "Zara Haas"
      - name: email
        type: string
        example: "zhaas@gmail.com"
  section-header:
    title: "Section Header"
    description: |
      Used on the profile page of site, used to differentiate current registries.
    fields:
    - name: heading
      type: string
      example: "Birthday"
  search-item:
    title: "Search Item"
    description: |
      Used to collect cards for the search function of site.
  profile-theme-section-birthday:
    title: "Profile Registry: Birthday"
    description: |
      Used highlight birthday registry on the profile page.
  profile-theme-section-grad:
    title: "Profile Registry: Graduation"
    description: |
      Used highlight graduation registry on the profile page.
  theme-section:
    title: "Theme Section"
    description: |
      This section is used to show a registry theme with the ability to scroll through the items included in the theme.
    fields:
      - name: heading
        type: string
        example: "Wedding"
      - name: image
        type: string
        example: "wedding-theme.jpg"
