title: "Cards"
description: |
  Cards should be used to showcase images, call to action and showcase information.

patterns:
  square-card:
    fields:
      - name: image
        type: string
        example: "1by1-placeholder-01.png"
      - name: heading
        type: string
        example: "Theme"
    title: "Square Card"
    description: |
      This type of card will be used in order to show images with no option of adding the item to a registry. Typically this card will be used on the profile of a user, when they are viewing their current registries.
  theme-card:
    fields:
      - name: image
        type: string
        example: "1by1-placeholder-01.png"
      - name: heading
        type: string
        example: "Theme"
    title: "Theme Card"
    description: |
      This type of card will be used in order to categorize a registry by theme. This will also be used to denote a category of items.
  add-card:
    fields:
      - name: image
        type: string
        example: "1by1-placeholder-01.png"
      - name: heading
        type: string
        example: "Theme"
      - name: url
        type: url
        example: "/profile/"
    title: "Add Card"
    description: |
      This type of card will be used when the user has the option to add the item to a registry. The addition symbol will act as a call to action for the user to add the item to their registry.
  product-card:
    fields:
      - name: heading
        type: string
        example: "Theme"
    title: "Product Card"
